#include "Defines.idl"

namespace MicaEditor
{
    [default_interface]
    runtimeclass MicaEditorControl : DUX.Controls.Control
    {
        MicaEditorControl();
        Int32 MyProperty;
        UInt64 Scintilla(Int32 message, UInt64 wParam, UInt64 lParam);
    }
}
