#include "Defines.idl"
import "EditorWrapper.idl";
import "IEditorAccess.idl";

namespace WinUIEditor
{
    [default_interface]
    [webhosthidden]
    runtimeclass CodeEditorControl : DUX.Controls.Control, IEditorAccess
    {
        CodeEditorControl();
        Editor Editor { get; };
        String HighlightingLanguage { get; set; };
        event Windows.Foundation.EventHandler<DUX.ElementTheme> DefaultColorsChanged;
        event Windows.Foundation.EventHandler<DUX.ElementTheme> SyntaxHighlightingApplied;
        void ApplyDefaultsToDocument();
        void ResetLexer();
        Boolean IsVerticalResizingEnabled { get; set; };
    }
}
