#include "Defines.idl"
import "EditorWrapper.idl";

namespace WinUIEditor
{
    [default_interface]
    [webhosthidden]
    runtimeclass CodeEditorControl : DUX.Controls.Control
    {
        CodeEditorControl();
        UInt64 SendMessage(ScintillaMessage message, UInt64 wParam, UInt64 lParam);
        Editor Editor { get; };
        String HighlightingLanguage { get; set; };
        event Windows.Foundation.EventHandler<DUX.ElementTheme> DefaultColorsChanged;
        event Windows.Foundation.EventHandler<DUX.ElementTheme> SyntaxHighlightingApplied;
    }
}
